import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Nav from "~/components/shared/nav/nav";
import { locales } from "~/navigation";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import { getServerAuthSession } from "~/server/auth";
import SessionProvider from "~/components/session-provider/session-provider";
import { NextIntlClientProvider } from "next-intl";
import { Toaster } from "~/components/ui/sonner";
import NavContextProvider from "~/context/nav-context-provider";
import Footer from "~/components/shared/footer/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  unstable_setRequestLocale(locale);

  const session = await getServerAuthSession();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`font-sans ${inter.variable} bg-white bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px]`}
      >
        <SessionProvider session={session}>
          <NextIntlClientProvider messages={messages}>
            <NavContextProvider>
              <Nav />
              {children}
              <Footer />
              <Toaster richColors />
            </NavContextProvider>
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
