import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Nav from "~/components/shared/nav/nav";
import { locales } from "~/navigation";
import { unstable_setRequestLocale } from "next-intl/server";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={`font-sans ${inter.variable}`}>
        {/* <Nav /> */}
        {children}
      </body>
    </html>
  );
}
